# Generated by Django 3.2.16 on 2023-08-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variatio_value',
            new_name='variation_value',
        ),
    ]
