# Generated by Django 5.0.7 on 2024-12-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variationcategory_alter_variation_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.variation'),
        ),
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
    ]
