# Generated by Django 5.1.6 on 2025-05-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debtscards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="hash_id",
            field=models.CharField(
                blank=True, editable=False, max_length=255, unique=True
            ),
        ),
    ]
