# Generated by Django 5.1.1 on 2025-04-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtscards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtaccount',
            name='hash_id',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
