# Generated by Django 5.2.7 on 2026-07-28 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtscards', '0002_client_hash_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono / Celular'),
        ),
        migrations.AddField(
            model_name='client',
            name='sector',
            field=models.CharField(blank=True, help_text='Ej: Sector Brinos, P.J. Santos Chocano, J.L. Ortiz', max_length=100, verbose_name='Sector / Zona'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección de Domicilio'),
        ),
        migrations.AlterField(
            model_name='client',
            name='know_name',
            field=models.CharField(max_length=150, verbose_name='Nombre Completo / Conocido'),
        ),
        migrations.AlterField(
            model_name='client',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud GPS'),
        ),
        migrations.AlterField(
            model_name='client',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud GPS'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de Usuario'),
        ),
        migrations.CreateModel(
            name='DebtCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='Nº de Tarjeta / Ficha')),
                ('article_description', models.CharField(help_text='Ej: 1 Multiuso Melamine x 160', max_length=255, verbose_name='Artículo(s) comprados')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total Deuda (S/)')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Restante (S/)')),
                ('payment_frequency', models.CharField(choices=[('S', 'Semanal'), ('Q', 'Quincenal'), ('M', 'Mensual')], default='S', max_length=1, verbose_name='Frecuencia de Pago Pactada')),
                ('agreed_quota', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cuota Pactada (S/)')),
                ('start_date', models.DateField(verbose_name='Fecha de Emisión / Venta')),
                ('status', models.CharField(choices=[('active', 'Activa (En cobro)'), ('paid', 'Cancelada / Pagada'), ('overdue', 'Vencida'), ('closed', 'Cerrada / Anulada')], default='active', max_length=20, verbose_name='Estado de Deuda')),
                ('hash_id', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_cards', to='debtscards.client', verbose_name='Cliente')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_cards', to=settings.AUTH_USER_MODEL, verbose_name='Cobrador Asignado')),
            ],
            options={
                'verbose_name': 'Tarjeta de Deuda',
                'verbose_name_plural': 'Tarjetas de Deudas',
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Fecha del Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado (S/)')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo Restante (Resta S/)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observaciones / Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debtscards.debtcard', verbose_name='Tarjeta de Deuda')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cobrador que Recibió')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'verbose_name_plural': 'Pagos de Cuotas',
                'ordering': ['payment_date', 'created_at'],
            },
        ),
    ]
