# Generated by Django 3.2.5 on 2023-09-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completred', 'Completado'), ('Accepted', 'Aceptado'), ('New', 'Nuevo'), ('Canceled', 'Cancelado')], default='New', max_length=50),
        ),
    ]
