# Generated by Django 5.0.7 on 2024-11-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completred', 'Completado'), ('Canceled', 'Cancelado'), ('Accepted', 'Aceptado'), ('New', 'Nuevo')], default='New', max_length=50),
        ),
    ]
