# Generated by Django 5.0.7 on 2024-12-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completred', 'Completado'), ('New', 'Nuevo'), ('Canceled', 'Cancelado'), ('Accepted', 'Aceptado')], default='New', max_length=50),
        ),
    ]
