# Generated by Django 5.1.1 on 2025-02-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_deleted_at_order_deleted_by_order_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Cancelado'), ('New', 'Nuevo'), ('Completred', 'Completado'), ('Accepted', 'Aceptado')], default='New', max_length=50),
        ),
    ]
