# Generated by Django 5.1.1 on 2025-02-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='dni',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Aceptado'), ('New', 'Nuevo'), ('Canceled', 'Cancelado'), ('Completred', 'Completado')], default='New', max_length=50),
        ),
    ]
