# Generated by Django 5.1.1 on 2025-02-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Cancelado'), ('Completred', 'Completado'), ('Accepted', 'Aceptado'), ('New', 'Nuevo')], default='New', max_length=50),
        ),
    ]
