# Generated by Django 5.1.6 on 2025-05-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "Nuevo"),
                    ("Completred", "Completado"),
                    ("Accepted", "Aceptado"),
                    ("Canceled", "Cancelado"),
                ],
                default="New",
                max_length=50,
            ),
        ),
    ]
