# Generated by Django 3.2.16 on 2023-08-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20230830_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Cancelado'), ('Completred', 'Completado'), ('New', 'Nuevo'), ('Accepted', 'Aceptado')], default='New', max_length=50),
        ),
    ]
