# Generated by Django 3.2.16 on 2023-08-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Nuevo'), ('Completred', 'Completado'), ('Accepted', 'Aceptado'), ('Canceled', 'Cancelado')], default='New', max_length=50),
        ),
    ]
