# Generated by Django 5.1.1 on 2025-02-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_order_total_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Nuevo'), ('Completred', 'Completado'), ('Accepted', 'Aceptado'), ('Canceled', 'Cancelado')], default='New', max_length=50),
        ),
    ]
